spring.application.name=taskreminder


# Database connection
spring.datasource.url=jdbc:mysql://localhost:3306/taskreminderdb
spring.datasource.username=root
spring.datasource.password=vignesh

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Server port
server.port=8080

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=your-email@gmail.com
spring.mail.password=abcd efgh ijkl mnop

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true